[window]
opacity = 1.0

[font]
size = 10

[font.bold]
family = "IBM Plex Mono"
style = "Bold"

[font.bold_italic]
family = "IBM Plex Mono"
style = "Bold Italic"

[font.italic]
family = "IBM Plex Mono"
style = "Italic"

[font.normal]
family = "IBM Plex Mono"
style = "Regular"

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[colors.normal]
black = "#202020"
red = "#404040"
green = "#606060"
yellow = "#808080"
blue = "#a0a0a0"
magenta = "#c0c0c0"
cyan = "#e0e0e0"
white = "#ffffff"

[colors.bright]
black = "#202020"
red = "#404040"
green = "#606060"
yellow = "#808080"
blue = "#a0a0a0"
magenta = "#c0c0c0"
cyan = "#e0e0e0"
white = "#ffffff"
